### ISSUE TITLE
nrf52840键盘

### ISSUE THREAD

**Issue by eos21** [myst729/xtrm#1]
感谢Duplex Matrixn提示，请问你做过nrf52840 双模键盘吗

**Comment by myst729** [comment]
目前只做过单模的，在准备看蓝牙的资料

**Comment by myst729** [comment]
![image](https://user-images.githubusercontent.com/519733/89178702-c85a0000-d5c0-11ea-8ac9-1a20eb33dac7.png)

不用Duplex Grid的话，也可以通过类似这样的方式减少GPIO的消耗，布线会稍微简单一些
